import { Router } from "express";
import { authRouter } from "./auth.js";
import { usersRouter } from "./users.js";
import { tasksRouter } from "./tasks.js";
import { eventsRouter } from "./events.js";
import { notesRouter } from "./notes.js";
import { projectsRouter } from "./projects.js";
import { tagsRouter } from "./tags.js";
import { habitsRouter } from "./habits.js";
import { goalsRouter } from "./goals.js";
import { chatRouter } from "./chat.js";
import { browserRouter } from "./browser.js";
import { remindersRouter } from "./reminders.js";
import { subscriptionsRouter } from "./subscriptions.js";
import { timeRouter } from "./time.js";
import { notificationsRouter } from "./notifications.js";
import { inboxRouter } from "./inbox.js";
import { inboxMailRouter } from "./inboxMail.js";
import { searchRouter } from "./search.js";
import { statsRouter } from "./stats.js";
import { calendarRouter, calendarFeedRouter } from "./calendar.js";
import { trashRouter } from "./trash.js";
import { adminRouter } from "./admin.js";
import { transferRouter } from "./transfer.js";
import { alertsRouter } from "./alerts.js";
import { pushRouter } from "./push.js";
import { mascotRouter } from "./mascot.js";
import { aiRouter } from "./ai.js";
import { telegramRouter } from "./telegram.js";
import { weatherRouter } from "./weather.js";
import { spotifyRouter } from "./spotify.js";
import { radioRouter } from "./radio.js";
import { vaultRouter } from "./vault.js";
import { messagingRouter } from "./messaging.js";
import { integrationsRouter } from "./integrations.js";
import { appInstallersRouter, appUpdaterRouter } from "./appInstallers.js";
import { APP_VERSION } from "../lib/brand.js";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => res.json({ ok: true, service: "dayly-api", version: APP_VERSION, time: new Date().toISOString() }));

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/tasks", tasksRouter);
apiRouter.use("/events", eventsRouter);
apiRouter.use("/notes", notesRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/tags", tagsRouter);
apiRouter.use("/habits", habitsRouter);
apiRouter.use("/goals", goalsRouter);
apiRouter.use("/chat", chatRouter);
apiRouter.use("/browser", browserRouter);
apiRouter.use("/reminders", remindersRouter);
apiRouter.use("/subscriptions", subscriptionsRouter);
apiRouter.use("/time", timeRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/inbox/mailboxes", inboxMailRouter);
apiRouter.use("/inbox", inboxRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/stats", statsRouter);
apiRouter.use("/calendar", calendarFeedRouter);
apiRouter.use("/calendar", calendarRouter);
apiRouter.use("/trash", trashRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/integrations", integrationsRouter);
apiRouter.use("/transfer", transferRouter);
apiRouter.use("/alerts", alertsRouter);
apiRouter.use("/push", pushRouter);
apiRouter.use("/mascot", mascotRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/telegram", telegramRouter);
apiRouter.use("/weather", weatherRouter);
apiRouter.use("/spotify", spotifyRouter);
apiRouter.use("/radio", radioRouter);
apiRouter.use("/vault", vaultRouter);
apiRouter.use("/messaging", messagingRouter);
apiRouter.use("/app/updater", appUpdaterRouter);
apiRouter.use("/app/installers", appInstallersRouter);
