-- AlterTable
ALTER TABLE `User` ADD COLUMN `themeScheduleEnabled` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `User` ADD COLUMN `themeDarkStartMin` INTEGER NOT NULL DEFAULT 1200;
ALTER TABLE `User` ADD COLUMN `themeDarkEndMin` INTEGER NOT NULL DEFAULT 360;
